services:
  franquicia-api:
    container_name: franquicia-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:8080"
    env_file:
      - ./.env
    restart: always
    networks:
      - franquicia-net

networks:
  franquicia-net:
    driver: bridge

